import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import HeaderTop from '../components/HeaderTop/HeaderTop'
import HeaderMenu from '../components/HeaderMenu/HeaderMenu'
import Breadcrumb from '../components/Breadcrumb/Breadcrumb'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Plastik-p2212',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        {/* Хедер */}
        <header className="headerWrapper">
          <div className="headerContainer">
            <HeaderTop />
            <HeaderMenu />
            <Breadcrumb />
          </div>
        </header>

        {/* Основний контент */}
        <main className="container">{children}</main>

        {/* Футер */}
        <footer className="footerWrapper">
          <div className="footerContainer">
            <p>© 2024 Plastik-p2212. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
